name: multiple jobs series

on: [push]

jobs:
  run-first-job:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello World"
      - name: multiline script
        run: |
          node -v
          npm -v
  run-second-job:
    runs-on: windows-latest
    needs: ["run-first-job"]
    steps:
      - name: directory powershell
        run: Get-Location
      - name: directory bash
        run: pwd
        shell: bash
     
