name: shell commands 

on: [push]

jobs:
  run-shell-command:
    runs-on: python
    steps:
      - name: python command
        run: |
          import platform
          print
          (platform.processor())
     
 
