name: Python commands 

on: [push]

jobs:
  run-python-command:
    runs-on: ubuntu-latest
    steps:
      - name: python commands
        run: |
          import platform
          print
          (platform.processor())
        shell: python
